"""
Centralized SQLite database for storing final filtered trading signals.

This module provides a unified interface for storing and querying trading signals
generated by the bulk strategy scanner with filtering applied.
"""

import sqlite3
import pandas as pd
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any
import logging

logger = logging.getLogger(__name__)

class TradingSignalsDB:
    """Centralized database for trading signals with filtering results."""
    
    def __init__(self, db_path: str = "results/trading_signals.db"):
        """Initialize the trading signals database.
        
        Args:
            db_path: Path to the SQLite database file
        """
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self.init_database()
    
    def init_database(self):
        """Initialize the database schema."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS daily_signals (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    scan_date TEXT NOT NULL,
                    symbol TEXT NOT NULL,
                    exchange TEXT NOT NULL,
                    instrument_type TEXT NOT NULL,
                    strategy TEXT NOT NULL,
                    model TEXT NOT NULL,
                    prediction_date TEXT NOT NULL,
                    raw_signal TEXT,
                    filtered_signal TEXT NOT NULL,
                    filter_applied BOOLEAN DEFAULT FALSE,
                    filter_name TEXT,
                    profile_name TEXT,
                    threshold REAL,
                    confidence REAL DEFAULT 0,
                    last_price REAL DEFAULT 0,
                    data_points INTEGER DEFAULT 0,
                    strategy_config TEXT,
                    cache_status TEXT,
                    method TEXT,  -- 'fast_cache' or 'full_strategy'
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(scan_date, symbol, exchange, strategy, model) ON CONFLICT REPLACE
                )
            """)
            
            # Create indexes for common queries
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_daily_signals_date 
                ON daily_signals(scan_date)
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_daily_signals_symbol 
                ON daily_signals(symbol, exchange)
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_daily_signals_strategy 
                ON daily_signals(strategy, model)
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_daily_signals_signal 
                ON daily_signals(filtered_signal)
            """)
            
            conn.commit()
            logger.info(f"Initialized trading signals database: {self.db_path}")
    
    def insert_signal(self, signal_data: Dict[str, Any]) -> bool:
        """Insert or update a trading signal record.
        
        Args:
            signal_data: Dictionary containing signal information
            
        Returns:
            True if successful, False otherwise
        """
        try:
            with sqlite3.connect(self.db_path) as conn:
                # Extract data with defaults
                record = {
                    'scan_date': signal_data.get('scan_date', datetime.now().strftime('%Y-%m-%d')),
                    'symbol': signal_data.get('symbol', ''),
                    'exchange': signal_data.get('exchange', 'US'),
                    'instrument_type': signal_data.get('type', signal_data.get('instrument_type', 'UNKNOWN')),
                    'strategy': signal_data.get('strategy', ''),
                    'model': signal_data.get('model', ''),
                    'prediction_date': signal_data.get('prediction_date', ''),
                    'raw_signal': signal_data.get('original_signal', signal_data.get('raw_signal')),
                    'filtered_signal': signal_data.get('t1_signal', signal_data.get('filtered_signal', 'HOLD')),
                    'filter_applied': bool(signal_data.get('filter_applied', False)),
                    'filter_name': signal_data.get('filter_name'),
                    'profile_name': signal_data.get('profile_name'),
                    'threshold': signal_data.get('threshold'),
                    'confidence': signal_data.get('context_score', 0),
                    'last_price': signal_data.get('last_price', 0),
                    'data_points': signal_data.get('data_points', 0) if isinstance(signal_data.get('data_points'), int) else 0,
                    'strategy_config': signal_data.get('strategy_config', ''),
                    'cache_status': signal_data.get('cache_status', 'unknown'),
                    'method': signal_data.get('method', 'unknown')
                }
                
                conn.execute("""
                    INSERT OR REPLACE INTO daily_signals (
                        scan_date, symbol, exchange, instrument_type, strategy, model,
                        prediction_date, raw_signal, filtered_signal, filter_applied,
                        filter_name, profile_name, threshold, confidence, last_price,
                        data_points, strategy_config, cache_status, method
                    ) VALUES (
                        :scan_date, :symbol, :exchange, :instrument_type, :strategy, :model,
                        :prediction_date, :raw_signal, :filtered_signal, :filter_applied,
                        :filter_name, :profile_name, :threshold, :confidence, :last_price,
                        :data_points, :strategy_config, :cache_status, :method
                    )
                """, record)
                
                conn.commit()
                logger.debug(f"Inserted signal: {record['symbol']} -> {record['filtered_signal']}")
                return True
                
        except Exception as e:
            logger.error(f"Error inserting signal: {e}")
            return False
    
    def insert_batch(self, signals: List[Dict[str, Any]], scan_date: Optional[str] = None) -> int:
        """Insert multiple signals in a batch.
        
        Args:
            signals: List of signal dictionaries
            scan_date: Override scan date for all signals
            
        Returns:
            Number of signals successfully inserted
        """
        if not scan_date:
            scan_date = datetime.now().strftime('%Y-%m-%d')
        
        inserted_count = 0
        for signal_data in signals:
            signal_data['scan_date'] = scan_date
            if self.insert_signal(signal_data):
                inserted_count += 1
        
        logger.info(f"Inserted {inserted_count}/{len(signals)} signals to database")
        return inserted_count
    
    def get_latest_signals(self, limit: int = 50) -> pd.DataFrame:
        """Get the most recent trading signals.
        
        Args:
            limit: Maximum number of signals to return
            
        Returns:
            DataFrame with latest signals
        """
        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT * FROM daily_signals 
                ORDER BY scan_date DESC, created_at DESC 
                LIMIT ?
            """
            return pd.read_sql_query(query, conn, params=[limit])
    
    def get_signals_by_date(self, date: str) -> pd.DataFrame:
        """Get all signals for a specific date.
        
        Args:
            date: Date in YYYY-MM-DD format
            
        Returns:
            DataFrame with signals for the date
        """
        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT * FROM daily_signals 
                WHERE scan_date = ? 
                ORDER BY symbol, strategy, model
            """
            return pd.read_sql_query(query, conn, params=[date])
    
    def get_signals_by_symbol(self, symbol: str, exchange: str = 'US', days: int = 30) -> pd.DataFrame:
        """Get recent signals for a specific symbol.
        
        Args:
            symbol: Trading symbol
            exchange: Exchange code
            days: Number of days to look back
            
        Returns:
            DataFrame with symbol's recent signals
        """
        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT * FROM daily_signals 
                WHERE symbol = ? AND exchange = ?
                AND scan_date >= date('now', '-{} days')
                ORDER BY scan_date DESC
            """.format(days)
            return pd.read_sql_query(query, conn, params=[symbol, exchange])
    
    def get_buy_sell_signals(self, date: Optional[str] = None) -> pd.DataFrame:
        """Get all BUY and SELL signals (excluding HOLD).
        
        Args:
            date: Optional date filter (YYYY-MM-DD)
            
        Returns:
            DataFrame with actionable signals
        """
        with sqlite3.connect(self.db_path) as conn:
            if date:
                query = """
                    SELECT * FROM daily_signals 
                    WHERE filtered_signal IN ('BUY', 'SELL') AND scan_date = ?
                    ORDER BY scan_date DESC, symbol
                """
                return pd.read_sql_query(query, conn, params=[date])
            else:
                query = """
                    SELECT * FROM daily_signals 
                    WHERE filtered_signal IN ('BUY', 'SELL')
                    ORDER BY scan_date DESC, symbol
                """
                return pd.read_sql_query(query, conn)
    
    def get_filter_effectiveness(self, days: int = 30) -> pd.DataFrame:
        """Analyze filter effectiveness over time.
        
        Args:
            days: Number of days to analyze
            
        Returns:
            DataFrame with filter statistics
        """
        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT 
                    scan_date,
                    strategy,
                    model,
                    filter_name,
                    profile_name,
                    COUNT(*) as total_signals,
                    SUM(CASE WHEN filter_applied = 1 THEN 1 ELSE 0 END) as filtered_signals,
                    SUM(CASE WHEN filtered_signal = 'BUY' THEN 1 ELSE 0 END) as buy_signals,
                    SUM(CASE WHEN filtered_signal = 'SELL' THEN 1 ELSE 0 END) as sell_signals,
                    SUM(CASE WHEN filtered_signal = 'HOLD' THEN 1 ELSE 0 END) as hold_signals,
                    AVG(threshold) as avg_threshold,
                    AVG(confidence) as avg_confidence
                FROM daily_signals 
                WHERE scan_date >= date('now', '-{} days')
                GROUP BY scan_date, strategy, model, filter_name, profile_name
                ORDER BY scan_date DESC
            """.format(days)
            return pd.read_sql_query(query, conn)
    
    def get_signal_summary(self) -> Dict[str, Any]:
        """Get overall database statistics.
        
        Returns:
            Dictionary with summary statistics
        """
        with sqlite3.connect(self.db_path) as conn:
            # Total signals
            total = conn.execute("SELECT COUNT(*) FROM daily_signals").fetchone()[0]
            
            # Date range
            date_range = conn.execute("""
                SELECT MIN(scan_date) as earliest, MAX(scan_date) as latest 
                FROM daily_signals
            """).fetchone()
            
            # Signal distribution
            signal_dist = pd.read_sql_query("""
                SELECT filtered_signal, COUNT(*) as count 
                FROM daily_signals 
                GROUP BY filtered_signal
            """, conn)
            
            # Recent activity
            recent = conn.execute("""
                SELECT COUNT(*) FROM daily_signals 
                WHERE scan_date >= date('now', '-7 days')
            """).fetchone()[0]
            
            return {
                'total_signals': total,
                'earliest_date': date_range[0] if date_range[0] else None,
                'latest_date': date_range[1] if date_range[1] else None,
                'signal_distribution': signal_dist.to_dict('records'),
                'recent_7_days': recent,
                'database_size': f"{self.db_path.stat().st_size / 1024:.1f} KB" if self.db_path.exists() else "0 KB"
            }
    
    def vacuum(self):
        """Optimize database performance."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("VACUUM")
            logger.info("Database vacuumed successfully")
    
    def export_to_csv(self, output_path: str, date_filter: Optional[str] = None) -> bool:
        """Export signals to CSV file.
        
        Args:
            output_path: Path for output CSV file
            date_filter: Optional date to filter (YYYY-MM-DD)
            
        Returns:
            True if successful
        """
        try:
            if date_filter:
                df = self.get_signals_by_date(date_filter)
            else:
                df = self.get_latest_signals(limit=10000)  # Large limit for export
                
            df.to_csv(output_path, index=False)
            logger.info(f"Exported {len(df)} signals to {output_path}")
            return True
        except Exception as e:
            logger.error(f"Error exporting to CSV: {e}")
            return False